### PR TITLE
在 actor 中使用 "PrimaryActorTick.bCanEverTick" 代替 "bCanEverTick" 

### PR DESCRIPTION
**Pull request by PredawnRaziel**
use "PrimaryActorTick.bCanEverTick" instead of "bCanEverTick" in actor.

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/sluaunreal?pullRequest=65) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/sluaunreal?pullRequest=65) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/sluaunreal?pullRequest=65) it.</sub>

**Comment by pangweiwei** [comment]
why you did this changes?

**Comment by PredawnRaziel** [comment]
Tick of actor seems controlled by `(self.)PrimaryActorTick.bCanEverTick`, not `(self.)bCanEverTick`.

It will cause exception but won't cause crash.

For example, in the file "LuaBpActor.lua": 

image

it will cause:

code2

(10+ actors were spawned so it were called 10+ times, and the function "bpcall" was called so there are many "called from blueprint 1024")

(sorry about this odd photo)

There is no exception if it is "`self.PrimaryActorTick.bCanEverTick = true`"

**Comment by pangweiwei** [comment]
bCanEverTick just is a simple flag to check whether enable tick function, this flag read by c++ code, c++ code will set PrimaryActorTick, see code:
virtual void BeginPlay() override { \
	if (!init(this, #NAME, LuaStateName, LuaFilePath)) return; \
		Super::BeginPlay(); \
                // here
		PrimaryActorTick.SetTickFunctionEnable(postInit("bCanEverTick")); \
	} \

throw exception just tell lua this property can't be set, lua will catch this exception and rawset it to self, so throw exception is proper behaviour。

ps: lua use c++ exception to handle script error.

**Comment by PredawnRaziel** [comment]
ahhh... I got it.
Thank you very much.

**Pull request closed without merging**
